kind = "api"
previewPath = "/"
title = "Tic Tac Toe AI"
version = "1.0.0"
id = "3B4_FFSkEVBkAeYMFRJ2e"

[[services]]
localPort = 8080
name = "Tic Tac Toe Server"
paths = ["/"]

[services.env]
PORT = "8080"

[services.development]
run = "npx nodemon /home/runner/workspace/server.js"
